// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyxsuelcatujkfmgwlmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5eHN1ZWxjYXR1amtmbWd3bG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzAwMTksImV4cCI6MjA2ODAwNjAxOX0.ZDhPvrBo1DOIsgfSaB_NU13-o5GkWIhmthZXzcuf9Rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});